development:
  sessions:
    default:

      database: link_up
      hosts:
        - localhost:27017
      options:
  options:
test:
  sessions:
    default:
      database: link_up
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0